name: Update README.md

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v24.1
    - name: GitHub Script
      uses: actions/github-script@v6.1.0
      with:
        script: |
          const changed = ${{ steps.changed-files.all_changed_files }}
          console.log(changed)
